name: Java CI with Gradle

on:
  push:
    branches: [ main ]
  pull_request:

permissions:
  contents: read

jobs:
  build-product-service:

    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: quarkus-product-service

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Build with Gradle
      run: ./gradlew build

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        registry: docker.io
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Create image
      run: |
        docker build -t ${IMAGE_NAME}-jvm . -f src/main/docker/Dockerfile.jvm
    - name: Push image
      run: |
        docker push ${IMAGE_NAME}-jvm:latest